name: Docker Push

on:
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                platform: ["linux/amd64", "linux/arm64"]
                tag: [
                    7.1-v1,
                    7.2-v1,
#                    7.3-v1,
                    7.3-v2,
                    7.3-v3,
                    7.3-v4,
                    7.4-v1,
                    7.4-v2,
                    7.4-v4,
                    7.4-v4.1,
                    7.4-v5,
                    8.0-base,
                    8.0-medialibrary,
                    8.1-base,
                    8.1-medialibrary,
                    8.2-base,
                    8.2-medialibrary,
                    8.3-base,
                    8.3-medialibrary,
                    8.4-base,
                    8.4-medialibrary,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Docker buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v3
                with:
                    version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }} ${{ matrix.platform }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
